### ISSUE TITLE
KubePersistentVolumeFillingUp: Message shows wrong Namespace

### ISSUE THREAD

**Issue by mhutter** [projectsyn/component-rancher-monitoring#13]
Example message:

> The PersistentVolume claimed by nginx-php in Namespace cattle-prometheus is only 0.01831% free.

This is wrong. `cattle-prometheus` is the namespace where Prometheus & AlertRules are deployed, NOT where the nginx-php PVC exists.

**Comment by mhutter** [comment]
Additionally, the alert is duplicated if the PV is mounted on multiple/different nodes.

Full set of labels:


Label | Value
-- | --
Label Alertname | KubePersistentVolumeFillingUp
Label Cluster | xxx
Label Cluster Name | xxx
Label Endpoint | https-metrics
Label Exported Namespace | xxx
Label Instance | 10.241.0.8:10250
Label Job | expose-kubelets-metrics
Label Namespace | cattle-prometheus
Label Node | aks-workers-20615988-vmss000014
Label Persistentvolumeclaim | nginx-php
Label Pod | prometheus-cluster-monitoring-0
Label Prometheus | cattle-prometheus/cluster-monitoring
Label Prometheus From | xxx
Label Service | expose-kubelets-metrics
Label Severity | critical
Label Tenant | t-ja3px4

**Comment by simu** [comment]
Looking at the alert provided by https://github.com/kubernetes-monitoring/kubernetes-mixin I noticed that the root cause of all the wrong namespace issues is most likely the way we federate metrics from the Rancher Prometheus instance, since the federated metrics will have label namespace=cattle-monitoring.

We might be able to address this by adjusting the federation config to not rename the metrics's original namespace label to `exported_namespace`.

**Comment by simu** [comment]
Another potential workaround until we can completely reengineer the federation might be to use [`label_replace()`](https://prometheus.io/docs/prometheus/latest/querying/functions/#label_replace)

**Comment by mhutter** [comment]
>since the federated metrics will have label namespace=cattle-monitoring.

Shouldn't `honor_labels` prevent this?

https://github.com/projectsyn/component-rancher-monitoring/blob/master/component/federation.jsonnet#L42

From the prometheus docs:
> To federate metrics from one server to another, configure your destination Prometheus server to scrape from the /federate endpoint of a source server, while also enabling the honor_labels scrape option (to not overwrite any labels exposed by the source server)

**Comment by simu** [comment]
> Shouldn't `honor_labels` prevent this?

Yes, but with a ServiceMonitor, additional relabelings get added which are processed after `honor_labels`. The most straightforward solution is to simply use a static scrape configuration instead of a ServiceMonitor for the federation, see #19.

**Comment by simu** [comment]
Turns out `honor_labels` was working as expected, but the `kubelet_volume_stats_*` and all other metrics collected by job "expose-kubelets-metrics" in the Rancher Prometheus already have the `exported_namespace` label. I've now updated the PR to fix the labels on all metrics which have both `exported_namespace` and `namespace`.
